name: Python test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      matrix:
        julia-version:
          - '1.3'
          - '1'
          - 'nightly'
        python-version:
          - 3.7
          - 3.8
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        arch:
          - x64
          - x86
        exclude:
          - os: ubuntu-latest
            arch: x86
          - os: macOS-latest
            arch: x86
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox
      - name: Set PYTHON and PYTHONPATH environment variable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo "PYTHON=${env:GITHUB_WORKSPACE}\.tox\py\scripts\python.exe" >> ${env:GITHUB_ENV}
          echo "PYTHONPATH=${env:GITHUB_WORKSPACE}\.tox\py\lib\site-packages" >> ${env:GITHUB_ENV}
      - name: Set PYTHON environment variable (Linux & MacOS)
        if: matrix.os != 'windows-latest'
        run: echo "PYTHON=${GITHUB_WORKSPACE}/.tox/py/bin/python" >> ${GITHUB_ENV}
      - name: Test with tox
        run: |
          echo ${{ env.PYTHON }}
          tox -e py
