name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version:
          - '1.6'
          - '1'
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - '3.10'
        os:
          - ubuntu-latest
        arch:
          - x64
        include:
          - julia-version: '1'
            python-version: '3.10'
            os: macOS-latest
            arch: x64
          - julia-version: '1'
            python-version: '3.10'
            os: windows-latest
            arch: x64
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
        with:
          cache-packages: 'false'
      - name: Test with tox
        run: python -m tox -- --cov=pycalibration --cov-report=xml -s
        env:
          TOXENV: py
          PYTHON: ${{ github.workspace }}/.tox/py/${{ fromJSON('["bin/python", "scripts/python.exe"]')[matrix.os == 'windows-latest'] }}
      - name: Upload coverage
        uses: codecov/codecov-action@v2